"""Base LLM Provider Interface for Flowsmith Universal Multi-Provider Engine.

Standardizes message representation, tool calling formats, token streaming,
and structured outputs across all modern frontier and local LLM providers.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, AsyncIterator


@dataclass
class ToolCall:
    id: str
    name: str
    arguments: dict[str, Any]


@dataclass
class LLMResponse:
    content: str = ""
    tool_calls: list[ToolCall] = field(default_factory=list)
    reasoning_content: str = ""  # Chain-of-thought for DeepSeek-R1, o1, o3-mini
    raw_response: dict[str, Any] = field(default_factory=dict)
    prompt_tokens: int = 0
    completion_tokens: int = 0
    finish_reason: str = "stop"

    @property
    def has_tool_calls(self) -> bool:
        return len(self.tool_calls) > 0


@dataclass
class LLMStreamChunk:
    delta_content: str = ""
    delta_reasoning: str = ""
    tool_call_chunks: list[dict[str, Any]] = field(default_factory=list)
    finish_reason: str | None = None


class BaseLLMProvider(ABC):
    """Abstract interface that all provider implementations must conform to."""

    provider_name: str = "base"

    @abstractmethod
    async def chat(
        self,
        messages: list[dict[str, Any]],
        *,
        model: str,
        temperature: float = 0.2,
        max_tokens: int | None = None,
        tools: list[dict[str, Any]] | None = None,
        tool_choice: str | dict[str, Any] = "auto",
        response_format: dict[str, Any] | None = None,
        api_key: str = "",
        base_url: str = "",
        timeout_s: float = 60.0,
        extra_headers: dict[str, str] | None = None,
    ) -> LLMResponse:
        """Send a chat completion request to the provider."""
        ...

    @abstractmethod
    def stream_chat(
        self,
        messages: list[dict[str, Any]],
        *,
        model: str,
        temperature: float = 0.2,
        max_tokens: int | None = None,
        tools: list[dict[str, Any]] | None = None,
        tool_choice: str | dict[str, Any] = "auto",
        api_key: str = "",
        base_url: str = "",
        timeout_s: float = 60.0,
        extra_headers: dict[str, str] | None = None,
    ) -> AsyncIterator[LLMStreamChunk]:
        """Stream token chunks as they are generated by the model."""
        ...
