"""Authentication metadata definitions and classification for all FlowSmith connectors.

Provides machine-readable classification into standard authentication methods:
- OAuth 2.0
- OAuth 2.0 + Refresh Token
- API Key
- Bearer Token
- Basic Auth
- Username + Password
- Client ID + Client Secret
- Service Account / JWT
- Client Credentials / S2S
- Custom Header
- No authentication required
"""
from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class AuthMethod(str, Enum):
    OAUTH2 = "OAuth 2.0"
    OAUTH2_REFRESH = "OAuth 2.0 + Refresh Token"
    API_KEY = "API Key"
    BEARER_TOKEN = "Bearer Token"
    BASIC_AUTH = "Basic Auth"
    USERNAME_PASSWORD = "Username + Password"
    CLIENT_ID_SECRET = "Client ID + Client Secret"
    SERVICE_ACCOUNT_JWT = "Service Account / JWT"
    CLIENT_CREDENTIALS_S2S = "Client Credentials / S2S"
    CUSTOM_HEADER = "Custom Header"
    NONE = "No authentication required"


class ImplementationStatus(str, Enum):
    AVAILABLE = "available"
    COMING_SOON = "coming_soon"
    NOT_IMPLEMENTED = "not_implemented"


class ConnectorAuthMetadata(BaseModel):
    connector_key: str
    display_name: str
    category: str
    auth_method: AuthMethod
    credential_type: Optional[str] = None
    status: ImplementationStatus = ImplementationStatus.AVAILABLE
    required_fields: List[str] = Field(default_factory=list)
    optional_fields: List[str] = Field(default_factory=list)
    secret_fields: List[str] = Field(default_factory=list)
    supports_oauth: bool = False
    supports_refresh: bool = False
    supports_test: bool = True
    description: str = ""
    notes: Optional[str] = None


# Authoritative classification catalog for FlowSmith connector ecosystem
CONNECTOR_AUTH_CATALOG: Dict[str, Dict[str, Any]] = {
    # --- Priority Enterprise CRM & ERP ---
    "salesforce": {
        "display_name": "Salesforce CRM",
        "category": "crm",
        "auth_method": AuthMethod.OAUTH2_REFRESH,
        "credential_type": "salesforce",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["instance_url"],
        "optional_fields": ["login_url", "client_id", "client_secret", "username", "password", "refresh_token", "oauth", "api_version"],
        "secret_fields": ["client_secret", "password", "refresh_token"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": True,
        "description": "Salesforce OAuth 2.0 Web Server Flow with PKCE or manual refresh token / password grant.",
    },
    "dynamics_crm": {
        "display_name": "Microsoft Dynamics 365 / Dataverse",
        "category": "crm",
        "auth_method": AuthMethod.CLIENT_CREDENTIALS_S2S,
        "credential_type": "dynamics_crm",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["resource_url"],
        "optional_fields": ["tenant_id", "client_id", "client_secret", "refresh_token", "oauth", "api_version"],
        "secret_fields": ["client_secret", "refresh_token"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": True,
        "description": "Azure AD / Entra ID OAuth2 Client Credentials (S2S) or Authorization Code.",
    },
    "zoho_crm": {
        "display_name": "Zoho CRM",
        "category": "crm",
        "auth_method": AuthMethod.OAUTH2,
        "credential_type": "zoho_crm",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": [],
        "secret_fields": ["access_token"],
        "supports_oauth": True,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Zoho CRM REST API v2 OAuth 2.0 Access Token.",
    },
    "hubspot": {
        "display_name": "HubSpot",
        "category": "crm",
        "auth_method": AuthMethod.OAUTH2_REFRESH,
        "credential_type": "hubspot",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": ["refresh_token", "client_id", "client_secret"],
        "secret_fields": ["access_token", "refresh_token", "client_secret"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": True,
        "description": "HubSpot OAuth 2.0 or Private App Access Token.",
    },
    "sap": {
        "display_name": "SAP S/4HANA",
        "category": "erp",
        "auth_method": AuthMethod.BASIC_AUTH,
        "credential_type": "sap",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["base_url"],
        "optional_fields": ["username", "password", "token", "api_key"],
        "secret_fields": ["password", "token", "client_secret", "api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "SAP S/4HANA Cloud / On-Premise Basic Auth, OAuth2 Bearer Token, or API Key.",
    },
    "servicenow": {
        "display_name": "ServiceNow",
        "category": "itsm",
        "auth_method": AuthMethod.BASIC_AUTH,
        "credential_type": "servicenow",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["instance"],
        "optional_fields": ["username", "password", "access_token"],
        "secret_fields": ["password", "access_token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "ServiceNow Instance Basic Auth or OAuth Bearer Token.",
    },
    "netsuite": {
        "display_name": "Oracle NetSuite",
        "category": "erp",
        "auth_method": AuthMethod.CLIENT_CREDENTIALS_S2S,
        "credential_type": "netsuite",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["account_id"],
        "optional_fields": ["token", "consumer_key", "consumer_secret", "token_id", "token_secret"],
        "secret_fields": ["token", "consumer_secret", "token_secret"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Oracle NetSuite Token-Based Authentication (TBA) or OAuth 2.0.",
    },
    "workday": {
        "display_name": "Workday",
        "category": "hr",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "workday",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["host", "tenant"],
        "optional_fields": ["token", "client_id", "client_secret"],
        "secret_fields": ["token", "client_secret", "refresh_token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Workday REST API OAuth2 Bearer Token.",
    },

    # --- Priority AI & LLM Providers ---
    "openai": {
        "display_name": "OpenAI",
        "category": "ai",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "openai",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": ["organization"],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "OpenAI API Key (sk-...).",
    },
    "anthropic": {
        "display_name": "Anthropic Claude",
        "category": "ai",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "anthropic",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Anthropic API Key (sk-ant-...).",
    },
    "gemini": {
        "display_name": "Google Gemini",
        "category": "ai",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "gemini",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Google AI Studio Gemini API Key (AIzaSy...).",
    },
    "open_router": {
        "display_name": "OpenRouter",
        "category": "ai",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "open_router",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": [],
        "secret_fields": ["access_token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "OpenRouter API Key.",
    },
    "groq": {
        "display_name": "Groq",
        "category": "ai",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "groq",
        "status": ImplementationStatus.COMING_SOON,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": False,
        "description": "Groq LPU Inference API Key (gsk_...). Connector unavailable — implementation pending.",
    },
    "deepseek": {
        "display_name": "DeepSeek",
        "category": "ai",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "deepseek",
        "status": ImplementationStatus.COMING_SOON,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": False,
        "description": "DeepSeek API Key (sk-...). Connector unavailable — implementation pending.",
    },

    # --- Collaboration & Productivity ---
    "slack": {
        "display_name": "Slack",
        "category": "communication",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "slack",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["bot_token"],
        "optional_fields": ["user_token"],
        "secret_fields": ["bot_token", "user_token"],
        "supports_oauth": True,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Slack Bot Token (xoxb-...) or User Token (xoxp-...).",
    },
    "msteams": {
        "display_name": "Microsoft Teams",
        "category": "communication",
        "auth_method": AuthMethod.OAUTH2_REFRESH,
        "credential_type": "microsoft_graph",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": ["refresh_token", "client_id", "client_secret", "tenant_id"],
        "secret_fields": ["access_token", "refresh_token", "client_secret"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": True,
        "description": "Microsoft Graph OAuth 2.0 Access Token with Teams scopes.",
    },
    "outlook": {
        "display_name": "Microsoft Outlook",
        "category": "communication",
        "auth_method": AuthMethod.OAUTH2_REFRESH,
        "credential_type": "microsoft_graph",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": ["refresh_token", "client_id", "client_secret", "tenant_id"],
        "secret_fields": ["access_token", "refresh_token", "client_secret"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": True,
        "description": "Microsoft Graph OAuth 2.0 Access Token with Mail scopes.",
    },
    "sharepoint": {
        "display_name": "Microsoft SharePoint",
        "category": "storage",
        "auth_method": AuthMethod.OAUTH2_REFRESH,
        "credential_type": "sharepoint",
        "status": ImplementationStatus.COMING_SOON,
        "required_fields": ["access_token"],
        "optional_fields": ["site_url", "tenant_id", "client_id", "client_secret"],
        "secret_fields": ["access_token", "client_secret"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": False,
        "description": "Microsoft Graph / SharePoint Online. Connector unavailable — implementation pending.",
    },
    "onedrive": {
        "display_name": "Microsoft OneDrive",
        "category": "storage",
        "auth_method": AuthMethod.OAUTH2_REFRESH,
        "credential_type": "onedrive",
        "status": ImplementationStatus.COMING_SOON,
        "required_fields": ["access_token"],
        "optional_fields": ["tenant_id", "client_id", "client_secret"],
        "secret_fields": ["access_token", "client_secret"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": False,
        "description": "Microsoft Graph / OneDrive for Business. Connector unavailable — implementation pending.",
    },
    "jira": {
        "display_name": "Jira",
        "category": "project_management",
        "auth_method": AuthMethod.BASIC_AUTH,
        "credential_type": "jira",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["domain", "email", "api_token"],
        "optional_fields": [],
        "secret_fields": ["api_token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Atlassian Cloud Jira Basic Auth (Email + API Token).",
    },
    "github": {
        "display_name": "GitHub",
        "category": "developer",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "github",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["token"],
        "optional_fields": [],
        "secret_fields": ["token"],
        "supports_oauth": True,
        "supports_refresh": False,
        "supports_test": True,
        "description": "GitHub Personal Access Token (ghp_...) or OAuth Token.",
    },
    "gitlab": {
        "display_name": "GitLab",
        "category": "developer",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "gitlab",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["token"],
        "optional_fields": ["base_url"],
        "secret_fields": ["token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "GitLab Personal Access Token (glpat-...) or Private Token.",
    },
    "bitbucket": {
        "display_name": "Bitbucket",
        "category": "developer",
        "auth_method": AuthMethod.BASIC_AUTH,
        "credential_type": "bitbucket",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["username", "app_password"],
        "optional_fields": [],
        "secret_fields": ["app_password"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Atlassian Bitbucket App Password.",
    },
    "notion": {
        "display_name": "Notion",
        "category": "productivity",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "notion",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Notion Internal Integration Token (secret_...).",
    },
    "airtable": {
        "display_name": "Airtable",
        "category": "productivity",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "airtable",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": True,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Airtable Personal Access Token (pat...).",
    },
    "asana": {
        "display_name": "Asana",
        "category": "project_management",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "asana",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": [],
        "secret_fields": ["access_token"],
        "supports_oauth": True,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Asana Personal Access Token or OAuth 2.0 Bearer Token.",
    },
    "clickup": {
        "display_name": "ClickUp",
        "category": "project_management",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "clickup",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "ClickUp Personal API Token (pk_...).",
    },
    "linear": {
        "display_name": "Linear",
        "category": "project_management",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "linear",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Linear Personal API Key (lin_api_...).",
    },
    "monday": {
        "display_name": "Monday.com",
        "category": "project_management",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "monday",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Monday.com API v2 Token.",
    },
    "trello": {
        "display_name": "Trello",
        "category": "project_management",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "trello",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key", "token"],
        "optional_fields": [],
        "secret_fields": ["token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Trello Developer API Key + User Token.",
    },
    "todoist": {
        "display_name": "Todoist",
        "category": "productivity",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "todoist",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_token"],
        "optional_fields": [],
        "secret_fields": ["api_token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Todoist API Token.",
    },
    "coda": {
        "display_name": "Coda",
        "category": "productivity",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "coda",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Coda Personal API Token.",
    },

    # --- Google Workspace ---
    "google_drive": {
        "display_name": "Google Drive",
        "category": "storage",
        "auth_method": AuthMethod.OAUTH2_REFRESH,
        "credential_type": "google_drive",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": ["refresh_token", "client_id", "client_secret"],
        "secret_fields": ["access_token", "refresh_token", "client_secret"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": True,
        "description": "Google Drive OAuth 2.0 Access & Refresh Token.",
    },
    "google_sheets": {
        "display_name": "Google Sheets",
        "category": "productivity",
        "auth_method": AuthMethod.OAUTH2_REFRESH,
        "credential_type": "google_sheets",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": ["refresh_token", "client_id", "client_secret"],
        "secret_fields": ["access_token", "refresh_token", "client_secret"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": True,
        "description": "Google Sheets OAuth 2.0 Access & Refresh Token.",
    },
    "google_docs": {
        "display_name": "Google Docs",
        "category": "productivity",
        "auth_method": AuthMethod.OAUTH2_REFRESH,
        "credential_type": "google_docs",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": ["refresh_token", "client_id", "client_secret"],
        "secret_fields": ["access_token", "refresh_token", "client_secret"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": True,
        "description": "Google Docs OAuth 2.0 Access & Refresh Token.",
    },
    "google_calendar": {
        "display_name": "Google Calendar",
        "category": "productivity",
        "auth_method": AuthMethod.OAUTH2_REFRESH,
        "credential_type": "google_calendar",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": ["refresh_token", "client_id", "client_secret"],
        "secret_fields": ["access_token", "refresh_token", "client_secret"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": True,
        "description": "Google Calendar OAuth 2.0 Access & Refresh Token.",
    },
    "gmail": {
        "display_name": "Gmail",
        "category": "communication",
        "auth_method": AuthMethod.OAUTH2_REFRESH,
        "credential_type": "gmail",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": ["refresh_token", "client_id", "client_secret"],
        "secret_fields": ["access_token", "refresh_token", "client_secret"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": True,
        "description": "Google Gmail OAuth 2.0 Access & Refresh Token.",
    },

    # --- Storage & Cloud Infrastructure ---
    "box": {
        "display_name": "Box",
        "category": "storage",
        "auth_method": AuthMethod.OAUTH2,
        "credential_type": "box",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": [],
        "secret_fields": ["access_token"],
        "supports_oauth": True,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Box Developer Token or OAuth 2.0 Access Token.",
    },
    "dropbox": {
        "display_name": "Dropbox",
        "category": "storage",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "dropbox",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": [],
        "secret_fields": ["access_token"],
        "supports_oauth": True,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Dropbox API Access Token.",
    },
    "s3": {
        "display_name": "AWS S3",
        "category": "storage",
        "auth_method": AuthMethod.CLIENT_CREDENTIALS_S2S,
        "credential_type": "aws_s3",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["aws_access_key_id", "aws_secret_access_key"],
        "optional_fields": ["aws_region", "aws_session_token", "endpoint_url"],
        "secret_fields": ["aws_secret_access_key", "aws_session_token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Amazon Web Services IAM Access Key & Secret.",
    },
    "bigquery": {
        "display_name": "Google Cloud BigQuery",
        "category": "database",
        "auth_method": AuthMethod.SERVICE_ACCOUNT_JWT,
        "credential_type": "bigquery",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["project_id", "access_token"],
        "optional_fields": [],
        "secret_fields": ["access_token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "GCP BigQuery Service Account / OAuth Access Token.",
    },

    # --- Databases ---
    "postgres": {
        "display_name": "PostgreSQL",
        "category": "database",
        "auth_method": AuthMethod.USERNAME_PASSWORD,
        "credential_type": "postgres",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["dsn"],
        "optional_fields": [],
        "secret_fields": ["dsn"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "PostgreSQL Connection URI (postgresql://user:pass@host:5432/db).",
    },
    "mysql": {
        "display_name": "MySQL",
        "category": "database",
        "auth_method": AuthMethod.USERNAME_PASSWORD,
        "credential_type": "mysql",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["dsn"],
        "optional_fields": [],
        "secret_fields": ["dsn"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "MySQL Connection URI (mysql+pymysql://user:pass@host:3306/db).",
    },
    "redis": {
        "display_name": "Redis",
        "category": "database",
        "auth_method": AuthMethod.USERNAME_PASSWORD,
        "credential_type": "redis",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["host"],
        "optional_fields": ["port", "password", "db"],
        "secret_fields": ["password"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Redis Connection Host, Port, and Password.",
    },
    "mongodb": {
        "display_name": "MongoDB",
        "category": "database",
        "auth_method": AuthMethod.USERNAME_PASSWORD,
        "credential_type": "mongodb",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["uri"],
        "optional_fields": [],
        "secret_fields": ["uri"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "MongoDB Connection String (mongodb+srv://user:pass@cluster...).",
    },
    "snowflake": {
        "display_name": "Snowflake",
        "category": "database",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "snowflake",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["account", "token"],
        "optional_fields": ["warehouse", "database", "schema", "role"],
        "secret_fields": ["token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Snowflake Account Identifier and SQL API Bearer Token / Keypair JWT.",
    },
    "supabase": {
        "display_name": "Supabase",
        "category": "database",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "supabase",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["project_url", "api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Supabase Project URL and Anon/Service Role API Key.",
    },
    "pinecone": {
        "display_name": "Pinecone",
        "category": "database",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "pinecone",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": ["environment"],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Pinecone Vector Database API Key.",
    },

    # --- Financial, Commerce & Payments ---
    "stripe": {
        "display_name": "Stripe",
        "category": "payments",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "stripe",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Stripe Secret Key (sk_live_... / sk_test_...).",
    },
    "shopify": {
        "display_name": "Shopify",
        "category": "ecommerce",
        "auth_method": AuthMethod.CUSTOM_HEADER,
        "credential_type": "shopify",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["shop_url", "access_token"],
        "optional_fields": [],
        "secret_fields": ["access_token"],
        "supports_oauth": True,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Shopify Admin API Access Token (shpat_...).",
    },
    "quickbooks": {
        "display_name": "QuickBooks Online",
        "category": "accounting",
        "auth_method": AuthMethod.OAUTH2_REFRESH,
        "credential_type": "quickbooks",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["realm_id", "access_token"],
        "optional_fields": ["refresh_token", "client_id", "client_secret"],
        "secret_fields": ["access_token", "refresh_token", "client_secret"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": True,
        "description": "Intuit QuickBooks OAuth 2.0 Token & Company Realm ID.",
    },
    "xero": {
        "display_name": "Xero",
        "category": "accounting",
        "auth_method": AuthMethod.OAUTH2,
        "credential_type": "xero",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["tenant_id", "access_token"],
        "optional_fields": [],
        "secret_fields": ["access_token"],
        "supports_oauth": True,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Xero Accounting OAuth 2.0 Access Token & Tenant ID.",
    },
    "docusign": {
        "display_name": "DocuSign",
        "category": "legal",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "docusign",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["account_id", "access_token"],
        "optional_fields": ["environment"],
        "secret_fields": ["access_token"],
        "supports_oauth": True,
        "supports_refresh": False,
        "supports_test": True,
        "description": "DocuSign eSignature OAuth Access Token & Account ID.",
    },

    # --- Communication, Marketing & Customer Support ---
    "sendgrid": {
        "display_name": "SendGrid",
        "category": "email",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "sendgrid",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Twilio SendGrid API Key (SG....).",
    },
    "twilio": {
        "display_name": "Twilio",
        "category": "telephony",
        "auth_method": AuthMethod.BASIC_AUTH,
        "credential_type": "twilio",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["account_sid", "auth_token"],
        "optional_fields": [],
        "secret_fields": ["auth_token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Twilio Account SID & Auth Token.",
    },
    "mailchimp": {
        "display_name": "Mailchimp",
        "category": "marketing",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "mailchimp",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key", "server_prefix"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Mailchimp Marketing API Key & Data Center Prefix (e.g. us19).",
    },
    "brevo": {
        "display_name": "Brevo (Sendinblue)",
        "category": "marketing",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "brevo",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Brevo v3 API Key (xkeysib-...).",
    },
    "activecampaign": {
        "display_name": "ActiveCampaign",
        "category": "marketing",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "activecampaign",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["account", "api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "ActiveCampaign Account Subdomain & API Key.",
    },
    "intercom": {
        "display_name": "Intercom",
        "category": "customer_support",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "intercom",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": [],
        "secret_fields": ["access_token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Intercom Developer Workspace Access Token.",
    },
    "freshdesk": {
        "display_name": "Freshdesk",
        "category": "customer_support",
        "auth_method": AuthMethod.BASIC_AUTH,
        "credential_type": "freshdesk",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["domain", "api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Freshdesk Domain & API Key.",
    },
    "freshsales": {
        "display_name": "Freshsales",
        "category": "crm",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "freshsales",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["domain", "api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Freshsales Domain & API Key.",
    },
    "zendesk": {
        "display_name": "Zendesk",
        "category": "customer_support",
        "auth_method": AuthMethod.BASIC_AUTH,
        "credential_type": "zendesk",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["subdomain", "email", "api_token"],
        "optional_fields": [],
        "secret_fields": ["api_token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Zendesk Subdomain, Agent Email, and API Token.",
    },
    "pagerduty": {
        "display_name": "PagerDuty",
        "category": "devops",
        "auth_method": AuthMethod.CUSTOM_HEADER,
        "credential_type": "pagerduty",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "PagerDuty REST API Token.",
    },
    "sentry": {
        "display_name": "Sentry",
        "category": "devops",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "sentry",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["auth_token"],
        "optional_fields": ["organization_slug"],
        "secret_fields": ["auth_token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Sentry User Auth Token or Integration Token.",
    },
    "typeform": {
        "display_name": "Typeform",
        "category": "forms",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "typeform",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["token"],
        "optional_fields": [],
        "secret_fields": ["token"],
        "supports_oauth": True,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Typeform Personal Access Token.",
    },
    "resend": {
        "display_name": "Resend",
        "category": "email",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "resend",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Resend API Key (re_...).",
    },
    "discord": {
        "display_name": "Discord",
        "category": "communication",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "discord",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["bot_token"],
        "optional_fields": [],
        "secret_fields": ["bot_token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Discord Bot Token.",
    },
    "whatsapp": {
        "display_name": "WhatsApp Business",
        "category": "communication",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "whatsapp",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token", "phone_number_id"],
        "optional_fields": [],
        "secret_fields": ["access_token"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Meta WhatsApp Business Cloud API Access Token.",
    },
    "zoom": {
        "display_name": "Zoom",
        "category": "communication",
        "auth_method": AuthMethod.CLIENT_CREDENTIALS_S2S,
        "credential_type": "zoom",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["account_id", "client_id", "client_secret"],
        "optional_fields": [],
        "secret_fields": ["client_secret"],
        "supports_oauth": True,
        "supports_refresh": True,
        "supports_test": True,
        "description": "Zoom Server-to-Server (S2S) OAuth App Credentials.",
    },
    "calendly": {
        "display_name": "Calendly",
        "category": "productivity",
        "auth_method": AuthMethod.BEARER_TOKEN,
        "credential_type": "calendly",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["access_token"],
        "optional_fields": [],
        "secret_fields": ["access_token"],
        "supports_oauth": True,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Calendly Personal Access Token or OAuth Bearer Token.",
    },
    "pipedrive": {
        "display_name": "Pipedrive",
        "category": "crm",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "pipedrive",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_token"],
        "optional_fields": ["company_domain"],
        "secret_fields": ["api_token"],
        "supports_oauth": True,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Pipedrive Personal API Token.",
    },
    "coin_gecko": {
        "display_name": "CoinGecko",
        "category": "finance",
        "auth_method": AuthMethod.API_KEY,
        "credential_type": "coin_gecko",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": ["api_key"],
        "optional_fields": [],
        "secret_fields": ["api_key"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "CoinGecko Demo / Pro API Key.",
    },

    # --- Generic & Universal HTTP ---
    "http": {
        "display_name": "Universal HTTP / REST API",
        "category": "core",
        "auth_method": AuthMethod.CUSTOM_HEADER,
        "credential_type": "http",
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": [],
        "optional_fields": ["api_key", "username", "password"],
        "secret_fields": ["api_key", "password"],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": True,
        "description": "Universal HTTP Request Authentication (API Key, Basic, Bearer, Custom Headers).",
    },

    # --- Utility / Non-Auth Connectors ---
    "schedule": {
        "display_name": "Schedule Trigger",
        "category": "core",
        "auth_method": AuthMethod.NONE,
        "credential_type": None,
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": [],
        "optional_fields": [],
        "secret_fields": [],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": False,
        "description": "Cron / Interval Workflow Trigger. No external authentication required.",
    },
    "webhook": {
        "display_name": "Webhook Connector",
        "category": "core",
        "auth_method": AuthMethod.NONE,
        "credential_type": None,
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": [],
        "optional_fields": [],
        "secret_fields": [],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": False,
        "description": "Inbound Webhook HTTP Trigger with optional HMAC signature verification.",
    },
    "dummy_json": {
        "display_name": "DummyJSON (Public Sandbox)",
        "category": "testing",
        "auth_method": AuthMethod.NONE,
        "credential_type": None,
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": [],
        "optional_fields": [],
        "secret_fields": [],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": False,
        "description": "Public test REST API. No authentication required.",
    },
    "frankfurter": {
        "display_name": "Frankfurter Currency API",
        "category": "finance",
        "auth_method": AuthMethod.NONE,
        "credential_type": None,
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": [],
        "optional_fields": [],
        "secret_fields": [],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": False,
        "description": "Open foreign exchange rates API. No authentication required.",
    },
    "httpbin": {
        "display_name": "HTTPBin Sandbox",
        "category": "testing",
        "auth_method": AuthMethod.NONE,
        "credential_type": None,
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": [],
        "optional_fields": [],
        "secret_fields": [],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": False,
        "description": "HTTP request & response service for live verification.",
    },
    "json_placeholder": {
        "display_name": "JSONPlaceholder",
        "category": "testing",
        "auth_method": AuthMethod.NONE,
        "credential_type": None,
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": [],
        "optional_fields": [],
        "secret_fields": [],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": False,
        "description": "Free fake REST API for testing and prototyping.",
    },
    "open_notify": {
        "display_name": "Open Notify ISS Tracker",
        "category": "testing",
        "auth_method": AuthMethod.NONE,
        "credential_type": None,
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": [],
        "optional_fields": [],
        "secret_fields": [],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": False,
        "description": "Public ISS telemetry and astronaut tracking API.",
    },
    "poke_api": {
        "display_name": "PokéAPI",
        "category": "testing",
        "auth_method": AuthMethod.NONE,
        "credential_type": None,
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": [],
        "optional_fields": [],
        "secret_fields": [],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": False,
        "description": "Public RESTful Pokémon API. No authentication required.",
    },
}

# Auto-classify Open-Meteo public weather family
for meteo_variant in [
    "open_meteo", "open_meteo_air", "open_meteo_climate", "open_meteo_elevation",
    "open_meteo_ensemble", "open_meteo_flood", "open_meteo_historical_weather",
    "open_meteo_marine", "open_meteo_seasonal"
]:
    CONNECTOR_AUTH_CATALOG[meteo_variant] = {
        "display_name": f"Open-Meteo ({meteo_variant.replace('open_meteo_', '').replace('_', ' ').title()})",
        "category": "weather",
        "auth_method": AuthMethod.NONE,
        "credential_type": None,
        "status": ImplementationStatus.AVAILABLE,
        "required_fields": [],
        "optional_fields": [],
        "secret_fields": [],
        "supports_oauth": False,
        "supports_refresh": False,
        "supports_test": False,
        "description": "Open-Meteo public non-commercial weather API. No authentication required.",
    }


def get_connector_auth_metadata(connector_key: str) -> Optional[ConnectorAuthMetadata]:
    """Look up authentication metadata for a specific connector."""
    entry = CONNECTOR_AUTH_CATALOG.get(connector_key)
    if not entry:
        return None
    return ConnectorAuthMetadata(connector_key=connector_key, **entry)


def list_connector_auth_metadata() -> List[ConnectorAuthMetadata]:
    """Return complete authentication metadata list across all connectors."""
    out = []
    for k, v in sorted(CONNECTOR_AUTH_CATALOG.items()):
        out.append(ConnectorAuthMetadata(connector_key=k, **v))
    return out


def get_auth_classification_summary() -> Dict[str, Any]:
    """Compute audit summary counts across the connector catalog."""
    total = len(CONNECTOR_AUTH_CATALOG)
    by_auth_method: Dict[str, int] = {}
    by_status: Dict[str, int] = {}
    requiring_credentials = 0
    no_auth = 0

    for item in CONNECTOR_AUTH_CATALOG.values():
        method_str = item["auth_method"].value if isinstance(item["auth_method"], AuthMethod) else str(item["auth_method"])
        status_str = item["status"].value if isinstance(item["status"], ImplementationStatus) else str(item["status"])
        by_auth_method[method_str] = by_auth_method.get(method_str, 0) + 1
        by_status[status_str] = by_status.get(status_str, 0) + 1
        if item["auth_method"] == AuthMethod.NONE:
            no_auth += 1
        else:
            requiring_credentials += 1

    return {
        "total_connectors_discovered": total,
        "connectors_requiring_credentials": requiring_credentials,
        "connectors_no_auth_required": no_auth,
        "breakdown_by_auth_method": by_auth_method,
        "breakdown_by_implementation_status": by_status,
    }
