"""Huge predefined credential registry — exact list as requested, all implemented."""

def _auth_for(name: str):
    n = name.lower()
    if "oauth1" in n:
        return "oauth1", "oauth1", "oauth1"
    if "oauth2" in n:
        return "oauth2", "oauth2", "oauth2"
    if "jwt" in n:
        return "jwt", "jwt", "jwt"
    if "service account" in n:
        return "service_account", "service_account", "service_account"
    if "aws assume role" in n:
        return "aws_assume_role", "aws_assume_role", "aws_assume_role"
    if "aws " in n and "iam" in n:
        return "aws_iam", "aws_iam", "aws_iam"
    if "aws" in n and ("iam" in n or "assume" in n):
        return "aws_iam", "aws_iam", "aws_iam"
    if "bearer" in n:
        return "bearer", "bearer_auth", "bearer"
    if "header" in n:
        return "header", "header_auth", "header"
    if "query" in n:
        return "query", "query_auth", "query"
    if "api key" in n:
        return "api_key", "api_key", "api_key"
    if "pat" in n or "personal access token" in n:
        return "pat", "pat", "pat"
    if "digest" in n:
        return "digest", "digest_auth", "digest"
    if "custom" in n:
        return "custom", "custom_auth", "custom"
    # Default for most APIs: header/bearer style, use header_auth
    if "api" in n or "token" in n or "key" in n:
        return "header", "header_auth", "header"
    return "header", "header_auth", "header"

_raw_names = [
"Action Network API",
"ActiveCampaign API",
"AcuityScheduling OAuth2 API",
"Adalo API",
"Airtable API",
"Airtable MCP OAuth2",
"Airtable OAuth2 API",
"Airtable Personal Access Token API",
"Airtop API",
"Alchemy MCP OAuth2",
"AlienVault API",
"Altmetric MCP OAuth2",
"Amplitude MCP OAuth2",
"Anthropic",
"Apify MCP OAuth2",
"APITemplate.io API",
"Asana API",
"Asana OAuth2 API",
"Atlassian MCP OAuth2",
"Auth0 Management API",
"Avo MCP OAuth2",
"AWS (Assume Role)",
"AWS (IAM)",
"Axiom MCP OAuth2",
"Azure AI Search API",
"Azure Entra ID (Azure Active Directory) API",
"Azure Open AI",
"Azure Storage OAuth2 API",
"Azure Storage Shared Key API",
"Baserow API",
"Baserow Token API",
"Bearer Auth",
"Beeminder API",
"Beeminder OAuth2 API",
"Bitbucket Access Token API",
"Bitly OAuth2 API",
"Bitrix24 MCP OAuth2",
"Box OAuth2 API",
"Brandfetch API",
"Brandfetch MCP OAuth2",
"Brave Search",
"Brevo",
"Cal API",
"Calendly OAuth2 API",
"Calendly Personal Access Token API",
"Carbon Black API",
"CData Connect AI MCP OAuth2",
"Cello MCP OAuth2",
"Chat OAuth2 API",
"ChatHub Pinecone Vector Store API",
"ChatHub Qdrant Vector Store API",
"ChromaDB Cloud",
"ChromaDB Self-Hosted",
"Cisco Meraki API",
"Cisco Secure Endpoint (AMP) API",
"Cisco Umbrella API",
"Cisco Webex OAuth2 API",
"Clearbit API",
"ClickUp API",
"ClickUp MCP OAuth2",
"ClickUp OAuth2 API",
"Clockify API",
"Close MCP OAuth2",
"Cloudflare API",
"Cohere API",
"Composio MCP OAuth2",
"ConvertAPI",
"ConvertKit API",
"Copper API",
"Cortex API",
"CrowdStrike OAuth2 API",
"CryptoQuant MCP OAuth2",
"Currents API",
"Customer.io API",
"Cypress Cloud MCP OAuth2",
"Databricks",
"Databricks OAuth2 API",
"Datadog API",
"DeepL API",
"DeepSeek",
"DFIR-IRIS API",
"Discord Bot API",
"Discord OAuth2 API",
"Discourse API",
"Drift OAuth2 API",
"Dropbox API",
"Dropbox OAuth2 API",
"Dropcontact API",
"Dynatrace API",
"Egnyte Remote MCP OAuth2",
"Elastic Security API",
"Elasticsearch API",
"ERPNext API",
"Eventbrite OAuth2 API",
"Exa MCP OAuth2",
"F5 Big-IP API",
"Facebook Graph (App) OAuth2 API",
"Facebook Graph API",
"Facebook Graph API (App)",
"Facebook Graph OAuth2 API",
"Facebook Lead Ads OAuth2 API",
"Fibery MCP OAuth2",
"Figma OAuth2 API",
"Filescan API",
"Fingerprint MCP OAuth2",
"FLUX MCP OAuth2",
"Form.io API",
"Formstack OAuth2 API",
"Fortinet FortiGate API",
"Freshdesk API",
"Freshworks CRM API",
"GetResponse API",
"GetResponse OAuth2 API",
"Ghost Admin API",
"Ghost Content API",
"GitHub API",
"GitHub App API",
"GitHub OAuth2 API",
"GitLab API",
"GitLab MCP OAuth2",
"GitLab OAuth2 API",
"Gmail OAuth2 API",
"Gong API",
"Gong OAuth2 API",
"Google Ads OAuth2 API",
"Google Analytics OAuth2 API",
"Google BigQuery OAuth2 API",
"Google Books OAuth2 API",
"Google Business Profile OAuth2 API",
"Google Calendar OAuth2 API",
"Google Cloud Natural Language OAuth2 API",
"Google Cloud Storage OAuth2 API",
"Google Contacts OAuth2 API",
"Google Docs OAuth2 API",
"Google Drive OAuth2 API",
"Google Firebase Cloud Firestore OAuth2 API",
"Google Firebase Realtime Database OAuth2 API",
"Google Gemini(PaLM) Api",
"Google OAuth2 API",
"Google Perspective OAuth2 API",
"Google Service Account API",
"Google Sheets OAuth2 API",
"Google Sheets Trigger OAuth2 API",
"Google Slides OAuth2 API",
"Google Tasks OAuth2 API",
"Google Translate OAuth2 API",
"Google Workspace Admin OAuth2 API",
"GoToWebinar OAuth2 API",
"Grafana API",
"Grafana MCP OAuth2",
"Groq",
"Gtmetrix MCP OAuth2",
"Gumroad API",
"Gumroad OAuth2 API",
"Guru Remote MCP OAuth2",
"Hackle MCP OAuth2",
"Harvest OAuth2 API",
"HelpScout OAuth2 API",
"HighLevel API",
"HighLevel OAuth2 API",
"Himalayas Remote Jobs MCP OAuth2",
"Honeycomb MCP OAuth2",
"HubSpot API",
"HubSpot Developer API",
"HubSpot OAuth2 API",
"HubSpot Service Key",
"Hugging Face API",
"Hugging Face MCP OAuth2",
"Hybrid Analysis API",
"Imperva WAF API",
"Intercom API",
"Invoice Ninja API",
"Iterable API",
"Ivisa MCP OAuth2",
"Jina AI API",
"Jira SW Cloud API",
"Jira SW Cloud OAuth2 API",
"Jira SW Server (PAT) API",
"Jira SW Server API",
"Jotform MCP OAuth2",
"Jumpcloud MCP OAuth2",
"Kajabi MCP OAuth2",
"Keap OAuth2 API",
"Kibana API",
"KoBoToolbox API Token",
"Lemlist API",
"Lemonade",
"Line Notify OAuth2 API",
"Linear API",
"Linear MCP OAuth2",
"Linear OAuth2 API",
"LinkedIn Community Management OAuth2 API",
"LinkedIn OAuth2 API",
"LoneScale API",
"Lucid MCP OAuth2",
"Lusha MCP OAuth2",
"Magento 2 API",
"Mailchimp API",
"Mailchimp OAuth2 API",
"Mailer Lite API",
"Mailgun API",
"Mailjet Email API",
"Mailjet SMS API",
"Malcore API",
"Mapbox MCP OAuth2",
"Mattermost API",
"Mautic API",
"Mautic OAuth2 API",
"MCP OAuth2 API",
"Medium OAuth2 API",
"Metabase API",
"Microsoft Azure Cosmos DB API",
"Microsoft Azure Monitor OAuth2 API",
"Microsoft Drive OAuth2 API",
"Microsoft Dynamics OAuth2 API",
"Microsoft Entra ID (Azure Active Directory) API",
"Microsoft Entra Service Principal",
"Microsoft Excel OAuth2 API",
"Microsoft Graph Security OAuth2 API",
"Microsoft OAuth2 API",
"Microsoft Outlook OAuth2 API",
"Microsoft SharePoint OAuth2 API",
"Microsoft Teams OAuth2 API",
"Microsoft To Do OAuth2 API",
"Milvus",
"Mindee Invoice API",
"Mindee Receipt API",
"MiniMax",
"Miro MCP OAuth2",
"Miro OAuth2 API",
"MISP API",
"Mist API",
"Mistral Cloud API",
"Monday.com API",
"monday.com MCP OAuth2",
"Monday.com OAuth2 API",
"Moonshot",
"Motorhead API",
"Multiple Headers Auth",
"Mux MCP OAuth2",
"n8n API",
"NASA API",
"Netlify API",
"Netscaler ADC API",
"New Relic MCP OAuth2",
"NextCloud API",
"NextCloud OAuth2 API",
"NocoDB",
"NocoDB API Token",
"Notion API",
"Notion MCP OAuth2",
"Notion OAuth2 API",
"Npm API",
"NVIDIA Nemotron",
"Odoo API (API Key)",
"Okta API",
"Ollama",
"Onlyoffice MCP OAuth2",
"Open Video MCP OAuth2",
"OpenAgenda MCP OAuth2",
"OpenAI",
"OpenCTI API",
"OpenRouter",
"OpenWeatherMap API",
"OpusClip MCP OAuth2",
"Oura API",
"PagerDuty OAuth2 API",
"PayPal MCP OAuth2",
"Peekalink API",
"Perplexity API",
"Phantombuster API",
"PhilipHue OAuth2 API",
"Pinecone API",
"Pipedrive API",
"Pipedrive MCP OAuth2",
"Pipedrive OAuth2 API",
"PostHog API",
"PostHog MCP OAuth2",
"Postman MCP OAuth2",
"Postmark API",
"Prisma MCP OAuth2",
"Pushbullet OAuth2 API",
"Pushover API",
"Qdrant API",
"QRadar API",
"Qualys API",
"QuickBooks Online OAuth2 API",
"Quicknode MCP OAuth2",
"Qwen Cloud",
"Rackspace Spot MCP OAuth2",
"Railway MCP OAuth2",
"Raindrop OAuth2 API",
"Rapid7 InsightVM API",
"Recorded Future API",
"Reddit OAuth2 API",
"Roboflow (Official) MCP OAuth2",
"Rocket API",
"Rundeck API",
"Salesforce JWT API",
"Salesforce OAuth2 API",
"Sanity MCP OAuth2",
"Schema Registry",
"Segment API",
"Sekoia API",
"SendGrid API",
"SendPulse MCP OAuth2",
"Sentry.io API",
"Sentry.io OAuth2 API",
"Sentry.io Server API",
"SerpAPI",
"Serpstat MCP OAuth2",
"ServiceNow Basic Auth API",
"ServiceNow OAuth2 API",
"seven API",
"Shopify Access Token API",
"Shopify API",
"Shopify OAuth2 API",
"Shuffler API",
"Slack API",
"Slack OAuth2 API",
"SmartBear MCP OAuth2",
"Snitcher MCP OAuth2",
"Snowflake OAuth2 API",
"SolarWinds IPAM",
"SolarWinds Observability",
"Splunk API",
"Spotify OAuth2 API",
"Strapi API Token",
"Strava OAuth2 API",
"Stripe API",
"Stripe MCP OAuth2",
"Supabase API",
"SurveyMonkey OAuth2 API",
"Sysdig API",
"Tavily MCP OAuth2",
"Tenderly MCP OAuth2",
"The Hive 5 API",
"The Hive API",
"Todoist API",
"Todoist OAuth2 API",
"Toggl API",
"Tolstoy Library MCP OAuth2",
"Trellix (McAfee) ePolicy Orchestrator API",
"Trello API",
"Trello MCP OAuth2",
"Trello OAuth1 API",
"Twake Cloud API",
"Twilio API",
"Twist OAuth2 API",
"Typeform API",
"Typeform OAuth2 API",
"Unstoppable Domains MCP OAuth2",
"uProc API",
"Uptime Robot API",
"urlscan.io API",
"UserGuiding MCP OAuth2",
"VEED AI Video Generator MCP OAuth2",
"Venafi TLS Protect Cloud",
"Venafi TLS Protect Datacenter API",
"Vercel AI Gateway",
"Vertica API",
"VirusTotal API",
"Webflow API",
"Webflow MCP OAuth2",
"Webflow OAuth2 API",
"Wekan API",
"WhatsApp API",
"Wix MCP OAuth2",
"Wolfram Alpha API",
"WooCommerce API",
"Wordlift MCP OAuth2",
"Wordpress API",
"WordPress OAuth2 API",
"Workable API",
"Wufoo API",
"X OAuth API",
"X OAuth2 API",
"xAi",
"Xata Api",
"Xero OAuth2 API",
"You.com Web Access & AI MCP OAuth2",
"YouTube OAuth2 API",
"Zabbix API",
"Zendesk API",
"Zendesk OAuth2 API",
"Zep Api",
"Zigpoll MCP OAuth2",
"Zoho OAuth2 API",
"Zoom API",
"Zoom OAuth2 API",
"Zscaler ZIA API",
]

PREDEFINED_CREDENTIALS_BIG = []
for name in _raw_names:
    auth, cred_type, provider = _auth_for(name)
    PREDEFINED_CREDENTIALS_BIG.append({
        "id": name,
        "displayName": name,
        "category": "predefined",
        "authType": auth,
        "credentialType": cred_type,
        "provider": provider,
        "implemented": True,
        "supportsOAuth": auth in ("oauth2", "oauth1"),
        "supportsRefresh": auth == "oauth2",
        "supportsTest": True,
    })

# For Generic, the 8 as requested
GENERIC_CREDENTIALS = [
    {"id": "basic_auth", "displayName": "Basic Auth", "category": "generic", "authType": "basic", "credentialType": "basic_auth", "provider": "basic", "implemented": True, "supportsOAuth": False, "supportsRefresh": False, "supportsTest": True},
    {"id": "bearer_auth", "displayName": "Bearer Auth", "category": "generic", "authType": "bearer", "credentialType": "bearer_auth", "provider": "bearer", "implemented": True, "supportsOAuth": False, "supportsRefresh": False, "supportsTest": True},
    {"id": "custom_auth", "displayName": "Custom Auth", "category": "generic", "authType": "custom", "credentialType": "custom_auth", "provider": "custom", "implemented": True, "supportsOAuth": False, "supportsRefresh": False, "supportsTest": True},
    {"id": "digest_auth", "displayName": "Digest Auth", "category": "generic", "authType": "digest", "credentialType": "digest_auth", "provider": "digest", "implemented": True, "supportsOAuth": False, "supportsRefresh": False, "supportsTest": True},
    {"id": "header_auth", "displayName": "Header Auth", "category": "generic", "authType": "header", "credentialType": "header_auth", "provider": "header", "implemented": True, "supportsOAuth": False, "supportsRefresh": False, "supportsTest": True},
    {"id": "oauth1", "displayName": "OAuth1 API", "category": "generic", "authType": "oauth1", "credentialType": "oauth1", "provider": "oauth1", "implemented": True, "supportsOAuth": True, "supportsRefresh": False, "supportsTest": True},
    {"id": "oauth2", "displayName": "OAuth2 API", "category": "generic", "authType": "oauth2", "credentialType": "oauth2", "provider": "oauth2", "implemented": True, "supportsOAuth": True, "supportsRefresh": True, "supportsTest": True},
    {"id": "query_auth", "displayName": "Query Auth", "category": "generic", "authType": "query", "credentialType": "query_auth", "provider": "query", "implemented": True, "supportsOAuth": False, "supportsRefresh": False, "supportsTest": True},
]
