export const OPERATOR_CATEGORIES = [
  { id: 'string', label: 'String', icon: 'T' },
  { id: 'number', label: 'Number', icon: '#' },
  { id: 'dateTime', label: 'Date & Time', icon: 'D' },
  { id: 'boolean', label: 'Boolean', icon: 'B' },
  { id: 'array', label: 'Array', icon: ':=' },
  { id: 'object', label: 'Object', icon: '{ }' },
]

export const CATEGORY_OPERATORS = {
  string: [
    { value: 'exists', label: 'exists', unary: true },
    { value: 'does not exist', label: 'does not exist', unary: true },
    { value: 'is empty', label: 'is empty', unary: true },
    { value: 'is not empty', label: 'is not empty', unary: true },
    { value: 'is equal to', label: 'is equal to' },
    { value: 'is not equal to', label: 'is not equal to' },
    { value: 'contains', label: 'contains' },
    { value: 'does not contain', label: 'does not contain' },
    { value: 'starts with', label: 'starts with' },
    { value: 'does not start with', label: 'does not start with' },
    { value: 'ends with', label: 'ends with' },
    { value: 'does not end with', label: 'does not end with' },
    { value: 'matches regex', label: 'matches regex' },
    { value: 'does not match regex', label: 'does not match regex' },
  ],
  number: [
    { value: 'exists', label: 'exists', unary: true },
    { value: 'does not exist', label: 'does not exist', unary: true },
    { value: 'is empty', label: 'is empty', unary: true },
    { value: 'is not empty', label: 'is not empty', unary: true },
    { value: 'is equal to', label: 'is equal to' },
    { value: 'is not equal to', label: 'is not equal to' },
    { value: 'is greater than', label: 'is greater than' },
    { value: 'is greater than or equal to', label: 'is greater than or equal to' },
    { value: 'is less than', label: 'is less than' },
    { value: 'is less than or equal to', label: 'is less than or equal to' },
  ],
  dateTime: [
    { value: 'exists', label: 'exists', unary: true },
    { value: 'does not exist', label: 'does not exist', unary: true },
    { value: 'is empty', label: 'is empty', unary: true },
    { value: 'is not empty', label: 'is not empty', unary: true },
    { value: 'is equal to', label: 'is equal to' },
    { value: 'is not equal to', label: 'is not equal to' },
    { value: 'is after', label: 'is after' },
    { value: 'is before', label: 'is before' },
    { value: 'is after or equal to', label: 'is after or equal to' },
    { value: 'is before or equal to', label: 'is before or equal to' },
  ],
  boolean: [
    { value: 'exists', label: 'exists', unary: true },
    { value: 'does not exist', label: 'does not exist', unary: true },
    { value: 'is empty', label: 'is empty', unary: true },
    { value: 'is not empty', label: 'is not empty', unary: true },
    { value: 'is true', label: 'is true', unary: true },
    { value: 'is false', label: 'is false', unary: true },
    { value: 'is equal to', label: 'is equal to' },
    { value: 'is not equal to', label: 'is not equal to' },
  ],
  array: [
    { value: 'exists', label: 'exists', unary: true },
    { value: 'does not exist', label: 'does not exist', unary: true },
    { value: 'is empty', label: 'is empty', unary: true },
    { value: 'is not empty', label: 'is not empty', unary: true },
    { value: 'contains', label: 'contains' },
    { value: 'does not contain', label: 'does not contain' },
    { value: 'length equal to', label: 'length equal to' },
    { value: 'length not equal to', label: 'length not equal to' },
    { value: 'length greater than', label: 'length greater than' },
    { value: 'length less than', label: 'length less than' },
  ],
  object: [
    { value: 'exists', label: 'exists', unary: true },
    { value: 'does not exist', label: 'does not exist', unary: true },
    { value: 'is empty', label: 'is empty', unary: true },
    { value: 'is not empty', label: 'is not empty', unary: true },
  ],
}

export const UNARY_OPERATORS = new Set([
  'exists',
  'does not exist',
  'is empty',
  'is not empty',
  'is true',
  'is false',
])
