"""Local filesystem object store backend (development default)."""

from __future__ import annotations

from pathlib import Path

from app.config import get_settings
from app.objectstore import ObjectStore


class LocalObjectStore(ObjectStore):
    def __init__(self, base_path: str | None = None) -> None:
        settings = get_settings()
        raw = base_path or settings.object_store_local_path
        # Treat bucket as subdirectory when one is configured so local and
        # S3 layouts stay comparable; empty bucket → base path directly.
        if settings.object_store_bucket:
            self._base = Path(raw) / settings.object_store_bucket
        else:
            self._base = Path(raw)
        self._base.mkdir(parents=True, exist_ok=True)

    def _path(self, object_key: str) -> Path:
        # Prevent directory traversal: object_key is always generated by the
        # server (workspace_id/uuid_filename), never user-supplied paths.
        # Still normalize to avoid accidental absolute keys.
        safe = object_key.lstrip("/").replace("..", "_")
        p = (self._base / safe).resolve()
        # Belt-and-braces containment: after resolve(), refuse anything that
        # escaped the store root (absolute keys, symlinked children, ...).
        base = self._base.resolve()
        if p != base and base not in p.parents:
            raise ValueError(f"object key escapes store root: {object_key!r}")
        return p

    def put(self, object_key: str, data: bytes, mime_type: str = "application/octet-stream") -> None:
        p = self._path(object_key)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)

    def get(self, object_key: str) -> bytes:
        p = self._path(object_key)
        if not p.is_file():
            raise FileNotFoundError(object_key)
        return p.read_bytes()

    def delete(self, object_key: str) -> bool:
        p = self._path(object_key)
        if not p.exists():
            return False
        try:
            p.unlink()
            # Prune empty parent dirs up to base (best-effort).
            cur = p.parent
            while cur != self._base and cur.is_dir() and not any(cur.iterdir()):
                cur.rmdir()
                cur = cur.parent
        except FileNotFoundError:
            return False
        return True

    def exists(self, object_key: str) -> bool:
        return self._path(object_key).is_file()
