"""Live Certification Profile Generator (Phase 42).

Generates structured JSON certification profiles for all priority connectors across:
- Wave 1: Enterprise SaaS & ERP (Salesforce, Dynamics 365, HubSpot, ServiceNow, Jira, Slack, MSTeams, SAP, Workday, NetSuite)
- Wave 2: Cloud Infrastructure & Databases (AWS S3, Snowflake, BigQuery, Postgres, MongoDB, Redis, Google Drive, Google Sheets)
- Wave 3: E-Commerce, Payments & Communications (Stripe, Shopify, Xero, QuickBooks, SendGrid, Twilio, Box, DocuSign, Typeform, etc.)
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

WORKSPACE_ROOT = Path(r"c:\Flowsmith")
PROFILES_DIR = WORKSPACE_ROOT / "docs" / "integration-platform" / "LIVE_CERTIFICATION_PROFILES"


PROFILES_DATA: list[dict[str, Any]] = [
    # -------------------------------------------------------------
    # WAVE 1: Enterprise SaaS & Core ERP
    # -------------------------------------------------------------
    {
        "connector": "salesforce",
        "vendor": "Salesforce, Inc.",
        "wave": 1,
        "sandbox": "https://test.salesforce.com (Developer Edition / Scratch Org)",
        "required_credentials": ["SALESFORCE_INSTANCE_URL", "SALESFORCE_ACCESS_TOKEN", "SALESFORCE_REFRESH_TOKEN"],
        "required_scopes": ["api", "refresh_token", "offline_access"],
        "operations_to_test": ["query_records", "create_record", "get_record", "update_record", "delete_record"],
        "searches_to_test": ["query_records (SOQL parameterized search)"],
        "triggers_to_test": ["salesforce_cdc (Change Data Capture)", "salesforce_outbound_message"],
        "webhooks_to_test": ["apex_rest_webhook"],
        "pagination_to_test": ["nextRecordsUrl cursor traversal"],
        "dynamic_schema_to_test": ["SObject describe global and SObject describe layout"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "dynamics_crm",
        "vendor": "Microsoft Corporation",
        "wave": 1,
        "sandbox": "Microsoft 365 Developer Program / Dynamics 365 Sales Trial",
        "required_credentials": ["DYNAMICS_TENANT_ID", "DYNAMICS_CLIENT_ID", "DYNAMICS_CLIENT_SECRET", "DYNAMICS_RESOURCE_URL"],
        "required_scopes": ["https://admin.services.crm.dynamics.com/.default"],
        "operations_to_test": ["list_accounts", "create_contact", "get_entity", "update_lead", "delete_entity"],
        "searches_to_test": ["filter_contacts ($filter OData query)"],
        "triggers_to_test": ["dynamics_webhook_trigger"],
        "webhooks_to_test": ["dataverse_service_endpoint_webhook"],
        "pagination_to_test": ["@odata.nextLink pagination"],
        "dynamic_schema_to_test": ["OData $metadata EDMX entity model describe"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "hubspot",
        "vendor": "HubSpot, Inc.",
        "wave": 1,
        "sandbox": "HubSpot Developer Account / App Test Portal",
        "required_credentials": ["HUBSPOT_ACCESS_TOKEN", "HUBSPOT_CLIENT_SECRET"],
        "required_scopes": ["crm.objects.contacts.read", "crm.objects.contacts.write", "crm.schemas.contacts.read"],
        "operations_to_test": ["get_contacts", "create_contact", "search_contacts", "update_contact"],
        "searches_to_test": ["search_contacts (CRM filter groups)"],
        "triggers_to_test": ["contact_created_trigger"],
        "webhooks_to_test": ["hubspot_app_webhook (v3 event subscription)"],
        "pagination_to_test": ["paging.next.after cursor pagination"],
        "dynamic_schema_to_test": ["crm/v3/properties/contacts metadata schema describe"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "servicenow",
        "vendor": "ServiceNow, Inc.",
        "wave": 1,
        "sandbox": "ServiceNow Personal Developer Instance (PDI - developer.servicenow.com)",
        "required_credentials": ["SERVICENOW_INSTANCE_URL", "SERVICENOW_USERNAME", "SERVICENOW_PASSWORD"],
        "required_scopes": ["itil", "admin"],
        "operations_to_test": ["query_incidents", "create_incident", "get_incident", "update_incident"],
        "searches_to_test": ["query_incidents (sysparm_query)"],
        "triggers_to_test": ["business_rule_outbound_rest"],
        "webhooks_to_test": ["scripted_rest_api_webhook"],
        "pagination_to_test": ["sysparm_limit / sysparm_offset pagination"],
        "dynamic_schema_to_test": ["sys_dictionary schema inspection"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "jira",
        "vendor": "Atlassian, Inc.",
        "wave": 1,
        "sandbox": "Atlassian Developer Cloud Sandbox (go.atlassian.com/cloud-dev)",
        "required_credentials": ["JIRA_BASE_URL", "JIRA_USER_EMAIL", "JIRA_API_TOKEN"],
        "required_scopes": ["read:jira-work", "write:jira-work"],
        "operations_to_test": ["search_issues", "create_issue", "get_issue", "transition_issue"],
        "searches_to_test": ["search_issues (JQL queries)"],
        "triggers_to_test": ["jira:issue_created"],
        "webhooks_to_test": ["atlassian_connect_webhook"],
        "pagination_to_test": ["startAt / maxResults offset pagination"],
        "dynamic_schema_to_test": ["issue/createmeta custom field discovery"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "slack",
        "vendor": "Slack Technologies / Salesforce",
        "wave": 1,
        "sandbox": "Slack Sandbox Workspace (api.slack.com/developer-program)",
        "required_credentials": ["SLACK_BOT_TOKEN", "SLACK_SIGNING_SECRET"],
        "required_scopes": ["channels:read", "channels:history", "chat:write", "users:read"],
        "operations_to_test": ["auth_test", "list_channels", "post_message", "get_conversation_history"],
        "searches_to_test": ["search_messages (search.messages)"],
        "triggers_to_test": ["message.channels (Events API)"],
        "webhooks_to_test": ["slack_events_api (X-Slack-Signature / timestamp validation)"],
        "pagination_to_test": ["response_metadata.next_cursor pagination"],
        "dynamic_schema_to_test": ["STATIC_SCHEMA"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "msteams",
        "vendor": "Microsoft Corporation",
        "wave": 1,
        "sandbox": "Microsoft 365 Developer Sandbox (E5 Developer Tenant)",
        "required_credentials": ["MSTEAMS_TENANT_ID", "MSTEAMS_CLIENT_ID", "MSTEAMS_CLIENT_SECRET"],
        "required_scopes": ["https://graph.microsoft.com/.default"],
        "operations_to_test": ["list_teams", "list_channels", "post_chat_message"],
        "searches_to_test": ["list_channels (filter by display name)"],
        "triggers_to_test": ["graph_change_notification_trigger"],
        "webhooks_to_test": ["microsoft_graph_subscription_webhook"],
        "pagination_to_test": ["@odata.nextLink pagination"],
        "dynamic_schema_to_test": ["Graph API metadata"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "sap",
        "vendor": "SAP SE",
        "wave": 1,
        "sandbox": "SAP BTP Trial / SAP Cloud Appliance Library (CAL) S/4HANA Sandbox",
        "required_credentials": ["SAP_BASE_URL", "SAP_USERNAME", "SAP_PASSWORD", "SAP_CLIENT_ID"],
        "required_scopes": ["API_BUSINESS_PARTNER", "API_SALES_ORDER_SRV"],
        "operations_to_test": ["list_business_partners", "get_sales_order", "create_business_partner"],
        "searches_to_test": ["list_business_partners ($filter)"],
        "triggers_to_test": ["sap_event_mesh_trigger"],
        "webhooks_to_test": ["sap_enterprise_messaging_webhook"],
        "pagination_to_test": ["$top / $skip OData pagination"],
        "dynamic_schema_to_test": ["$metadata EDMX schema inspection"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "workday",
        "vendor": "Workday, Inc.",
        "wave": 1,
        "sandbox": "Workday Developer Preview Tenant (community.workday.com)",
        "required_credentials": ["WORKDAY_TENANT_URL", "WORKDAY_ISU_USERNAME", "WORKDAY_ISU_PASSWORD"],
        "required_scopes": ["Human_Resources", "Staffing"],
        "operations_to_test": ["get_workers", "get_organization", "execute_report"],
        "searches_to_test": ["get_workers (RaaS parameterized report)"],
        "triggers_to_test": ["workday_outbound_integration_trigger"],
        "webhooks_to_test": ["workday_event_notification"],
        "pagination_to_test": ["Page / Count XML pagination"],
        "dynamic_schema_to_test": ["RaaS WSDL / XSD dynamic schema parsing"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "netsuite",
        "vendor": "Oracle Corporation",
        "wave": 1,
        "sandbox": "Oracle NetSuite Release Preview / Sandbox Account",
        "required_credentials": ["NETSUITE_ACCOUNT_ID", "NETSUITE_CONSUMER_KEY", "NETSUITE_CONSUMER_SECRET", "NETSUITE_TOKEN_ID", "NETSUITE_TOKEN_SECRET"],
        "required_scopes": ["restlets", "rest_webservices", "suiteql"],
        "operations_to_test": ["execute_suiteql", "get_customer", "create_sales_order"],
        "searches_to_test": ["execute_suiteql (SuiteQL queries)"],
        "triggers_to_test": ["netsuite_user_event_script_trigger"],
        "webhooks_to_test": ["restlet_outbound_webhook"],
        "pagination_to_test": ["limit / offset SuiteQL pagination"],
        "dynamic_schema_to_test": ["SuiteQL record-catalog schema discovery"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },

    # -------------------------------------------------------------
    # WAVE 2: Cloud Infrastructure, Databases & Analytics
    # -------------------------------------------------------------
    {
        "connector": "s3",
        "vendor": "Amazon Web Services",
        "wave": 2,
        "sandbox": "AWS Free Tier Account / LocalStack S3 Sandbox",
        "required_credentials": ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION", "AWS_S3_TEST_BUCKET"],
        "required_scopes": ["s3:ListBucket", "s3:GetObject", "s3:PutObject", "s3:DeleteObject"],
        "operations_to_test": ["list_objects", "get_object", "put_object", "delete_object"],
        "searches_to_test": ["list_objects (prefix search)"],
        "triggers_to_test": ["s3_object_created_sns_sqs"],
        "webhooks_to_test": ["aws_sns_webhook_signature_verification"],
        "pagination_to_test": ["continuation-token / NextContinuationToken"],
        "dynamic_schema_to_test": ["STATIC_SCHEMA"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "snowflake",
        "vendor": "Snowflake, Inc.",
        "wave": 2,
        "sandbox": "Snowflake 30-Day Free Trial (snowflake.com/trial)",
        "required_credentials": ["SNOWFLAKE_ACCOUNT", "SNOWFLAKE_USER", "SNOWFLAKE_PASSWORD", "SNOWFLAKE_DATABASE", "SNOWFLAKE_SCHEMA", "SNOWFLAKE_WAREHOUSE"],
        "required_scopes": ["USAGE", "OPERATE", "SELECT", "INSERT"],
        "operations_to_test": ["execute_query", "list_tables", "describe_table"],
        "searches_to_test": ["execute_query (SQL SELECT WHERE)"],
        "triggers_to_test": ["snowflake_streams_trigger"],
        "webhooks_to_test": ["snowflake_external_function_webhook"],
        "pagination_to_test": ["SQL LIMIT / OFFSET pagination"],
        "dynamic_schema_to_test": ["INFORMATION_SCHEMA.COLUMNS table introspection"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "bigquery",
        "vendor": "Google Cloud",
        "wave": 2,
        "sandbox": "Google Cloud Free Tier / BigQuery Sandbox (without credit card)",
        "required_credentials": ["GOOGLE_APPLICATION_CREDENTIALS", "BIGQUERY_PROJECT_ID"],
        "required_scopes": ["https://www.googleapis.com/auth/bigquery"],
        "operations_to_test": ["query", "list_datasets", "list_tables", "get_table_metadata"],
        "searches_to_test": ["query (Standard SQL parameterized search)"],
        "triggers_to_test": ["bigquery_eventarc_trigger"],
        "webhooks_to_test": ["gcp_pubsub_push_webhook"],
        "pagination_to_test": ["pageToken / nextPageToken pagination"],
        "dynamic_schema_to_test": ["BigQuery schema field definitions"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "postgres",
        "vendor": "PostgreSQL Global Development Group",
        "wave": 2,
        "sandbox": "Local / Containerized PostgreSQL Sandbox (port 5432)",
        "required_credentials": ["POSTGRES_HOST", "POSTGRES_PORT", "POSTGRES_USER", "POSTGRES_PASSWORD", "POSTGRES_DB"],
        "required_scopes": ["CONNECT", "SELECT", "INSERT", "UPDATE", "DELETE"],
        "operations_to_test": ["execute_query", "list_tables", "describe_table"],
        "searches_to_test": ["execute_query (SQL parameterized filter)"],
        "triggers_to_test": ["logical_replication_cdc_trigger"],
        "webhooks_to_test": ["pg_notify_listener"],
        "pagination_to_test": ["LIMIT / OFFSET pagination"],
        "dynamic_schema_to_test": ["information_schema.columns introspection"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "mongodb",
        "vendor": "MongoDB, Inc.",
        "wave": 2,
        "sandbox": "MongoDB Atlas Free Shared Cluster (M0 Sandbox)",
        "required_credentials": ["MONGODB_URI", "MONGODB_DATABASE"],
        "required_scopes": ["readWrite"],
        "operations_to_test": ["find_documents", "insert_document", "update_document", "delete_document"],
        "searches_to_test": ["find_documents (MQL query filter)"],
        "triggers_to_test": ["mongodb_change_streams_trigger"],
        "webhooks_to_test": ["atlas_app_services_webhook"],
        "pagination_to_test": ["skip / limit / cursor pagination"],
        "dynamic_schema_to_test": ["BSON schema validator discovery"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "redis",
        "vendor": "Redis Ltd.",
        "wave": 2,
        "sandbox": "Local Redis Container (port 6379) / Redis Cloud Free Tier",
        "required_credentials": ["REDIS_URL"],
        "required_scopes": ["allcommands"],
        "operations_to_test": ["get", "set", "delete", "keys", "publish"],
        "searches_to_test": ["scan (SCAN match pattern)"],
        "triggers_to_test": ["redis_keyspace_notification_trigger"],
        "webhooks_to_test": ["redis_pubsub_webhook"],
        "pagination_to_test": ["SCAN cursor continuation"],
        "dynamic_schema_to_test": ["STATIC_SCHEMA"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "google_drive",
        "vendor": "Google LLC",
        "wave": 2,
        "sandbox": "Google Cloud Console Sandbox Project (Service Account)",
        "required_credentials": ["GOOGLE_SERVICE_ACCOUNT_JSON"],
        "required_scopes": ["https://www.googleapis.com/auth/drive.file"],
        "operations_to_test": ["list_files", "get_file_metadata", "upload_file", "delete_file"],
        "searches_to_test": ["list_files (q query string search)"],
        "triggers_to_test": ["drive_changes_watch_trigger"],
        "webhooks_to_test": ["google_drive_push_notification_webhook"],
        "pagination_to_test": ["pageToken / nextPageToken pagination"],
        "dynamic_schema_to_test": ["STATIC_SCHEMA"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "google_sheets",
        "vendor": "Google LLC",
        "wave": 2,
        "sandbox": "Google Cloud Console Sandbox Project (Service Account)",
        "required_credentials": ["GOOGLE_SERVICE_ACCOUNT_JSON"],
        "required_scopes": ["https://www.googleapis.com/auth/spreadsheets"],
        "operations_to_test": ["get_spreadsheet", "read_range", "append_rows"],
        "searches_to_test": ["read_range (A1 notation range search)"],
        "triggers_to_test": ["apps_script_on_change_trigger"],
        "webhooks_to_test": ["apps_script_do_post_webhook"],
        "pagination_to_test": ["Row offset pagination"],
        "dynamic_schema_to_test": ["Sheet header row dynamic column introspection"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },

    # -------------------------------------------------------------
    # WAVE 3: E-Commerce, Payments & Communications
    # -------------------------------------------------------------
    {
        "connector": "stripe",
        "vendor": "Stripe, Inc.",
        "wave": 3,
        "sandbox": "Stripe Test Mode (dashboard.stripe.com/test)",
        "required_credentials": ["STRIPE_API_KEY", "STRIPE_WEBHOOK_SECRET"],
        "required_scopes": ["rk_test_* restricted or sk_test_* secret keys"],
        "operations_to_test": ["get_balance", "list_customers", "create_customer", "create_payment_intent"],
        "searches_to_test": ["list_customers (email search filter)"],
        "triggers_to_test": ["payment_intent.succeeded"],
        "webhooks_to_test": ["stripe_webhook (Stripe-Signature timestamped HMAC validation)"],
        "pagination_to_test": ["starting_after cursor pagination"],
        "dynamic_schema_to_test": ["STATIC_SCHEMA"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "shopify",
        "vendor": "Shopify Inc.",
        "wave": 3,
        "sandbox": "Shopify Partner Development Store (partners.shopify.com)",
        "required_credentials": ["SHOPIFY_SHOP_DOMAIN", "SHOPIFY_ADMIN_ACCESS_TOKEN", "SHOPIFY_WEBHOOK_SECRET"],
        "required_scopes": ["read_products", "write_products", "read_orders"],
        "operations_to_test": ["list_products", "get_product", "create_product", "list_orders"],
        "searches_to_test": ["list_products (title query search)"],
        "triggers_to_test": ["orders/create"],
        "webhooks_to_test": ["shopify_webhook (X-Shopify-Hmac-Sha256 base64 validation)"],
        "pagination_to_test": ["page_info cursor pagination (Link header)"],
        "dynamic_schema_to_test": ["GraphQL Admin API schema describe"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "sendgrid",
        "vendor": "Twilio SendGrid",
        "wave": 3,
        "sandbox": "SendGrid Free Plan / Sandbox Mode (mail_settings.sandbox_mode=true)",
        "required_credentials": ["SENDGRID_API_KEY"],
        "required_scopes": ["mail.send", "templates.read"],
        "operations_to_test": ["send_mail", "list_templates", "get_verified_senders"],
        "searches_to_test": ["list_templates (filter by generation type)"],
        "triggers_to_test": ["event_webhook_delivered"],
        "webhooks_to_test": ["sendgrid_event_webhook (ECDSA signature verification)"],
        "pagination_to_test": ["page / page_size pagination"],
        "dynamic_schema_to_test": ["STATIC_SCHEMA"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "docusign",
        "vendor": "DocuSign, Inc.",
        "wave": 3,
        "sandbox": "DocuSign eSignature Developer Demo (account-d.docusign.com)",
        "required_credentials": ["DOCUSIGN_ACCOUNT_ID", "DOCUSIGN_ACCESS_TOKEN"],
        "required_scopes": ["signature", "extended"],
        "operations_to_test": ["list_envelopes", "create_envelope", "get_envelope", "list_templates"],
        "searches_to_test": ["list_envelopes (from_date / status search)"],
        "triggers_to_test": ["envelope-completed (DocuSign Connect)"],
        "webhooks_to_test": ["docusign_connect_hmac_webhook"],
        "pagination_to_test": ["start_position / count offset pagination"],
        "dynamic_schema_to_test": ["STATIC_SCHEMA"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "box",
        "vendor": "Box, Inc.",
        "wave": 3,
        "sandbox": "Box Developer Free Sandbox (account.box.com/signup/n/developer)",
        "required_credentials": ["BOX_CLIENT_ID", "BOX_CLIENT_SECRET", "BOX_DEVELOPER_TOKEN"],
        "required_scopes": ["root_readwrite", "manage_webhook"],
        "operations_to_test": ["get_current_user", "get_folder_items", "create_folder", "delete_folder"],
        "searches_to_test": ["search (query string search)"],
        "triggers_to_test": ["FILE.UPLOADED (Box Webhooks V2)"],
        "webhooks_to_test": ["box_v2_webhook_signature"],
        "pagination_to_test": ["marker / next_marker cursor pagination"],
        "dynamic_schema_to_test": ["STATIC_SCHEMA"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "typeform",
        "vendor": "Typeform SL",
        "wave": 3,
        "sandbox": "Typeform Free Plan (admin.typeform.com)",
        "required_credentials": ["TYPEFORM_ACCESS_TOKEN"],
        "required_scopes": ["forms:read", "forms:write", "responses:read", "webhooks:read", "webhooks:write"],
        "operations_to_test": ["list_forms", "get_form", "get_responses"],
        "searches_to_test": ["list_forms (search by form title)"],
        "triggers_to_test": ["form_response_submitted"],
        "webhooks_to_test": ["typeform_webhook_sha256_signature"],
        "pagination_to_test": ["page / page_size pagination"],
        "dynamic_schema_to_test": ["Dynamic form field question schema"],
        "expected_certification": "PRODUCTION_CERTIFIED",
    },
    {
        "connector": "http",
        "vendor": "Universal API Standard (W3C / IETF / OpenAPI)",
        "wave": 3,
        "sandbox": "Public Live Sandboxes: https://httpbin.org, https://jsonplaceholder.typicode.com",
        "required_credentials": [],
        "required_scopes": [],
        "operations_to_test": ["request (GET/POST/PUT/DELETE)", "search", "query"],
        "searches_to_test": ["search (query parameters)"],
        "triggers_to_test": ["http_inbound_webhook_trigger"],
        "webhooks_to_test": ["inbound_raw_http_webhook"],
        "pagination_to_test": ["page / offset / cursor configurable pagination"],
        "dynamic_schema_to_test": ["infer_json_schema dynamic runtime inference"],
        "expected_certification": "LIVE_API_VALIDATED",
    },
]


def generate_live_certification_profiles() -> None:
    PROFILES_DIR.mkdir(parents=True, exist_ok=True)
    count = 0
    for prof in PROFILES_DATA:
        key = prof["connector"]
        file_path = PROFILES_DIR / f"{key}.json"
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(prof, f, indent=2)
        count += 1
    print(f"Generated {count} Live Certification Profiles in {PROFILES_DIR}")


if __name__ == "__main__":
    generate_live_certification_profiles()
